## Config File for Web Application
## IMPORTANT: Indentation in this file must be 2 spaces!

## credentials
credentials:
  mongoDB_username: "placeholder_text_for_username"
  mongoDB_password: "placeholder_text_for_password"

## build settings
build:
  ## Can be set to dev or prod ->
  option: "dev"

  ## Can be set to unix or windows ->
  platform: "unix"

  ## Each below can be set to yes or no ->
  run_application: "yes"
  build_for_production: "no"

## dependency checking and installation
dependencies:
  ## Each below can be set to yes or no ->
  check_npm_version: "no"
  check_next_version: "no"
  force_npm_reinstall: "no"
  force_next_reinstall: "no"
